# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ main ] 

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      run: sh gradlew clean build
    - run: | 
            cd build/libs
            ls -lrt
    - uses: actions/upload-artifact@v3
      with:
        name: myartifact
        path: build/libs/cicdstudy-0.0.1-SNAPSHOT.jar
            
  publish:
  
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: ap-south-1
        
    - run: aws --version
    - run: aws s3 ls
    - uses: actions/download-artifact@v3
      with:
        name: myartifact
        
    - run: ls -lrt
    - run: aws s3 cp cicdstudy-0.0.1-SNAPSHOT.jar s3://devops-jiem-bucket-ugaji1/newapp-${GITHUB_RUN_ID}.jar
    
  deploy:
  
    runs-on: ubuntu-latest
    needs: publish
    
    steps:
    
    - run: echo "${GITHUB_RUN_ID}"
    - run: echo "##[set-output name=GITHUB_RUN_ID;]$(echo ${GITHUB_RUN_ID})"
      id: deploy
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: "ec2-user"
        key: ${{ secrets.SSH_KEY }}
        script: | 
          whoami
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.SSH_KEY }}
          export AWS_DEFAULT_REGION=ap-south-1
          
          aws -version
          
          aws s3 cp s3://devops-jiem-bucket-ugaji1/newapp-${{ steps.deploy.outputs.GITHUB_RUN_ID }}.jar app.jar
          
          nohup java -jar app.jar &            
    
        
